### PR TITLE
change to public fields of tag

### PR DESCRIPTION
**Pull request by MH4GF**
These fields would be very useful to have available for testing,
I would like to make them available to the public.

### CODE REVIEW

**Comment by marijnh** [comment]
In what situations are they useful?

**Comment by MH4GF** [comment]
https://github.com/ProseMirror/prosemirror-schema-list/blob/aa6f2a6c42ee0c23406b39a818d92f691068773e/test/test-commands.ts#L7-L15
Since tag returns pos, defining such a `selFor()` function has the advantage that the selection can be defined declaratively, increasing the readability of the test.

**Comment by marijnh** [comment]
Ah, you are talking about `tag`, not `flat`. I guess adding that to the return type there could make this a little more ergonomic. Adding `flat` seems to serve little purpose though (and is in fact incorrect, since that's not a property being added to `Node` instances, but an internally used alternative return type)

**Comment by MH4GF** [comment]
@marijnh thank you for response, Certainly for my use case, only `tag` was sufficient and I could not think of a case where `flat` would be needed. removed it: a9cb60b

**Pull request merged**
